Updated README
GoogleCloudPlatform/mongodb-docker pull request #68
Opened 2021-04-30 13:45 UTC by ekorolevich

+deleted folder with 3rd version

2021-05-10 18:38 UTC, vcanaa approved these changes

2021-05-13 10:53 UTC, ovk6 requested changes

2021-05-13 10:53 UTC, ovk6 commented on README.md
> +
Remove from this line forward

2021-05-13 10:53 UTC, ovk6 commented on README.md
> +Pull command (first install [gcloud](https://cloud.google.com/sdk/downloads)):
I'd split this section, here and in other READMEs:
```
    ### Prerequisites

    Configure [gcloud](https://cloud.google.com/sdk/gcloud/) as a Docker credential helper:

    ```shell
    gcloud auth configure-docker
    ```

    ### Pull command

    ```shell
    docker -- pull marketplace.gcr.io/google/mongodb4
    ```
```

2021-05-13 10:53 UTC, ovk6 commented on README.md
> +# <a name="about"></a>About
Change headers one level down (`# Upstream` -> `## Upstream`):

```
mongodb-docker
============

## Upstream
...

## Disclaimer
...

## About
...
```

2021-05-13 11:58 UTC, ovk6 approved these changes

2021-05-13 12:25 UTC, merged